In [1]:
import pandas as pd
import numpy as np
from gensim.models.word2vec import Word2Vec
import gensim.downloader as api
from sklearn.metrics.pairwise import cosine_similarity

print("loading language model")
# load language model (this takes a few minutes)
model = api.load('word2vec-google-news-300')
print("model loaded")

loading language model
[==================================================] 100.0% 1662.8/1662.8MB downloaded
model loaded


In [2]:
vectors = model.wv
del model
vectors.init_sims(True) # normalize the vectors (!), so we can use the dot product as similarity measure

print('embeddings loaded ')
print('loading docs ... ')

/Users/erindb/miniconda3/envs/ecj/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


embeddings loaded 
loading docs ... 


In [25]:
# vectors[["ADU", "housing"]]

array([[-3.75537425e-02, -8.87633935e-02,  4.03469950e-02,
        -3.66226584e-02, -2.70014517e-02, -4.50024195e-02,
         9.00048390e-03, -4.56231423e-02, -9.99364033e-02,
        -1.02807244e-03, -2.25012098e-02,  6.89002573e-02,
        -4.03469950e-02,  1.15454480e-01, -2.77773552e-02,
        -4.15884405e-02, -2.21908484e-02, -3.78641039e-02,
         6.12963969e-03,  1.37334969e-02, -6.26930222e-02,
         2.07942203e-02,  6.98313415e-02, -5.49339876e-02,
        -1.01177849e-01, -1.13475928e-03,  2.99498849e-02,
         1.31593272e-01, -4.00366336e-02,  2.52168719e-03,
         6.83765218e-04, -6.82795346e-02,  2.18804870e-02,
        -4.96578403e-02,  2.09494010e-02, -1.78457871e-02,
         6.05204925e-02, -1.03971101e-02, -7.75903761e-02,
        -2.76221745e-02,  6.54862747e-02,  9.31084529e-02,
        -5.86583242e-02,  1.31593272e-01, -7.64265191e-03,
         2.59927753e-03, -2.05614488e-03, -5.83479628e-02,
        -4.55843459e-04, -6.85898960e-02, -1.43542197e-0

In [224]:
keywords = ['housing', 'affordable', 'homelessness', 'ADU']

In [ ]:
directory = '../data/legistar_corpus'
import os
from autolocal.nlp import Tokenizer
from gensim.parsing.preprocessing import *

tokenizer = Tokenizer()

documents = []
document_sections = []
# section_length = 20 # lines
section_length = 100 # tokens
min_section_length = 5

docs_tokens = []

# TODO: is lowercasing necessary?
preprocess_filters = [
    lambda x: x.lower(),
    strip_punctuation,
    strip_numeric,
    strip_non_alphanum,
    strip_multiple_whitespaces,
    strip_numeric,
    remove_stopwords,
    strip_short
]

i=0
for filename in os.listdir(directory): 
    with open (os.path.join(directory, filename)) as f: 
        document_tokens = []
        document_str = f.read()
        document_segment_lines = []
        document_segment_tokens = []
        document_tokens = []
#         if i<100:
        if True:
            pages = document_str.split('\f')
            for p, page in enumerate(pages): 
                lines = page.split('\n')
                for line in lines:
                    line_tokens = preprocess_string(line, filters=preprocess_filters)
                    document_segment_lines.append(line)
                    document_segment_tokens += line_tokens
                    document_tokens += line_tokens
                    docs_tokens += line_tokens
                    if len(document_segment_tokens) >= section_length:
                        document_sections.append((
                            document_segment_tokens,
                            p,
                            filename,
                            "\n".join(document_segment_lines)
                        ))
                        document_segment_lines = []
                        document_segment_tokens = []
                if len(document_segment_tokens) >= min_section_length:
                    document_sections.append((
                        document_segment_tokens,
                        p,
                        filename,
                        "\n".join(document_segment_lines)
                    ))
                    document_segment_lines = []
                    document_segment_tokens = []
                documents.append(document_tokens)           
        i+=1
#         if i%100 == 0:
#             print(i)


In [ ]:
print(len(document_sections))
print(document_sections[0])

In [ ]:
# print(document_sections[0])
# print(document_sections[1])

* Inverse document frequency for each keyword
* For each document section, for each keyword, get average document similarity
    * for each word in the document section, for each keyword, get similarity of word vectors
    * average across the document
* For each document section, sum average document similarity, weighted by keyword inverse document frequency

In [ ]:
from collections import Counter
word_counts = Counter(docs_tokens)
smoothing = 100
doc_freqs = {}
doc_freq_total = 0
for w in word_counts:
    if w in vectors:
        doc_freqs[w] = word_counts[w] + smoothing
        doc_freq_total += word_counts[w] + smoothing
word_counts = None
doc_props = {w: doc_freqs[w]/doc_freq_total for w in doc_freqs}
inverse_doc_props = {w: (1/doc_props[w] if doc_props[w]>0 else 0) for w in doc_props}
# inverse_doc_props

In [ ]:
inverse_doc_props

In [ ]:
keyword_vectors = np.array([vectors[t] for t in keywords if t in inverse_doc_props])
keyword_weights = np.array([inverse_doc_props[t] for t in keywords if t in inverse_doc_props])
document_section_scores = []
for s, section in enumerate(document_sections):
        score = None
        section_tokens = section[0]
        section_vectors = np.array([vectors[t] for t in section_tokens if t in inverse_doc_props])
        if section_vectors.shape[0]>0:
#             section_weights = np.array([inverse_doc_props[t] for t in section_tokens if t in inverse_doc_props])
            similarities = cosine_similarity(section_vectors, keyword_vectors)
#             similarities = similarities * section_weights
#             similarities = similarities*(similarities>0.2)
            keyword_similarities = np.mean(similarities, axis=0)
#             keyword_similarities = np.average(similarities, axis=0, weights=section_weights)
            score = np.sum(keyword_similarities*keyword_weights)
        document_section_scores.append(score)

In [ ]:
max_score = np.max(np.array([s for s in document_section_scores if s!=None]))
print(max_score)
best_doc_index = [i for i, s in enumerate(document_section_scores) if s==max_score][0]
print(document_sections[best_doc_index])

In [ ]:
max_score = np.max(np.array([s for s in document_section_scores if s!=None]))
best_doc_indices = [i for i, s in enumerate(document_section_scores) if s!=None and s>2000]
best_doc_indices
for i in best_doc_indices:
    print(document_sections[i][3])
    print("~~~~")
# print(document_sections[best_doc_index])

In [ ]:
all_keywords = keywords
# How many documents does each keyword occur in?
keyword_doc_counts = {k: 0 for k in all_keywords}
keyword_doc_total = 0
for document in documents:
    for k in keyword_doc_counts:
        if k in document:
            keyword_doc_counts[k] += 1
            keyword_doc_total += 1
            
keyword_section_counts = {k: 0 for k in all_keywords}
keyword_section_total = 0
for document in document_sections:
    for k in keyword_section_counts:
        if k in document[0]:
            keyword_section_counts[k] += 1
            keyword_section_total += 1

In [ ]:
keyword_doc_proportions = {k: keyword_doc_counts[k]/keyword_doc_total for k in keyword_doc_counts}
keyword_section_proportions = {k: keyword_section_counts[k]/keyword_section_total for k in keyword_section_counts}
print(keyword_doc_proportions)
print(keyword_section_proportions)

In [ ]:
inverse_doc_freq = {k: 1/(keyword_doc_proportions[k]) if keyword_doc_proportions[k]>0 else 0 for k in keyword_doc_proportions}
inverse_doc_freq

In [ ]:
keyword_vectors = np.array([vectors[t] for t in keywords if t in vectors])
keyword_weights = np.array([inverse_doc_freq[t] for t in keywords if t in vectors])
document_section_scores = []
for s, section in enumerate(document_sections):
#     if s < 10:
        score = None
        section_tokens = section[0]
#         print("read tokens")
        # get word vectors
        section_vectors = np.array([vectors[t] for t in section_tokens if t in vectors])
#         print("word vectors looked up")
        if section_vectors.shape[0]>0:
            similarities = cosine_similarity(section_vectors, keyword_vectors)
            similarities = similarities*(similarities>0.1)
#             print("similarities computed")
            keyword_similarities = np.mean(similarities, axis=0)
            score = np.sum(keyword_similarities*keyword_weights)
        document_section_scores.append(score)
# print(document_section_scores)

In [ ]:
max_score = np.max(np.array([s for s in document_section_scores if s!=None]))
print(max_score)
best_doc_index = [i for i, s in enumerate(document_section_scores) if s==max_score][0]
print(document_sections[best_doc_index])

# max_score = np.max(np.array([s for s in document_section_scores if s!=None]))
# best_doc_indices = [i for i, s in enumerate(document_section_scores) if s!=None and s>20]
# best_doc_indices
# for i in best_doc_indices:
#     print(document_sections[i])
# # print(document_sections[best_doc_index])

In [ ]:
# why are these the same?
print(" ".join(document_sections[0][0]))
print(" ".join(document_sections[1][0]))

In [147]:
sims = cosine_similarity(np.array(vectors[["ADU", "applesauce"]]), np.array(vectors[["housing", "after", "attachment", "cooking"]]))
sims*(sims>0)

array([[ 0.1902841 , -0.        ,  0.12652467,  0.01557165],
       [ 0.06678405,  0.04545134,  0.05078512,  0.29745492]],
      dtype=float32)

In [171]:
print(all_keywords)
cosine_similarity(np.array(vectors[all_keywords]), np.array(vectors[["housing", "after", "attachment", "cooking"]]))

['housing', 'affordable', 'homelessness', 'accessory', 'dwelling', 'unit', 'ADU']


array([[ 1.        ,  0.0360411 ,  0.03927992,  0.09836677],
       [ 0.31637853, -0.06969636,  0.02391504,  0.14009611],
       [ 0.45313504, -0.01476945,  0.01381858,  0.09197982],
       [ 0.0892075 ,  0.03608286,  0.21938115,  0.07302914],
       [ 0.40325326,  0.02292117,  0.17923255,  0.15913229],
       [ 0.16630656,  0.12939759,  0.13552879,  0.03668242],
       [ 0.1902841 , -0.09115382,  0.12652467,  0.01557165]],
      dtype=float32)